//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Good_Teacher.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormatStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormatStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Good_Teacher.Strings.FormatStrings", typeof(FormatStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A3 (1123x1587).
        /// </summary>
        public static string A3 {
            get {
                return ResourceManager.GetString("A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A4 (794x1123).
        /// </summary>
        public static string A4 {
            get {
                return ResourceManager.GetString("A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A5 (559x794).
        /// </summary>
        public static string A5 {
            get {
                return ResourceManager.GetString("A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cm (Centimeters).
        /// </summary>
        public static string cm {
            get {
                return ResourceManager.GetString("cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        public static string cmO {
            get {
                return ResourceManager.GetString("cmO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codabar.
        /// </summary>
        public static string Codabar {
            get {
                return ResourceManager.GetString("Codabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code128.
        /// </summary>
        public static string Code128 {
            get {
                return ResourceManager.GetString("Code128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default (1280x720).
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN-13.
        /// </summary>
        public static string EAN13 {
            get {
                return ResourceManager.GetString("EAN13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN-8.
        /// </summary>
        public static string EAN8 {
            get {
                return ResourceManager.GetString("EAN8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full HD (1920x1080).
        /// </summary>
        public static string FullHD {
            get {
                return ResourceManager.GetString("FullHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal.
        /// </summary>
        public static string Ideal {
            get {
                return ResourceManager.GetString("Ideal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inch (Inches).
        /// </summary>
        public static string inches {
            get {
                return ResourceManager.GetString("inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string inO {
            get {
                return ResourceManager.GetString("inO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jpg.
        /// </summary>
        public static string Jpg {
            get {
                return ResourceManager.GetString("Jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string PDF {
            get {
                return ResourceManager.GetString("PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Png.
        /// </summary>
        public static string Png {
            get {
                return ResourceManager.GetString("Png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pt (Points).
        /// </summary>
        public static string points {
            get {
                return ResourceManager.GetString("points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pt.
        /// </summary>
        public static string ptO {
            get {
                return ResourceManager.GetString("ptO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Px (Pixels).
        /// </summary>
        public static string px {
            get {
                return ResourceManager.GetString("px", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to px.
        /// </summary>
        public static string pxO {
            get {
                return ResourceManager.GetString("pxO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code.
        /// </summary>
        public static string QRCode {
            get {
                return ResourceManager.GetString("QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVGA 4:3 (800x600).
        /// </summary>
        public static string SVGA {
            get {
                return ResourceManager.GetString("SVGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UHD (3840x2160).
        /// </summary>
        public static string UHD {
            get {
                return ResourceManager.GetString("UHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WXGA 16:10 (1280x800).
        /// </summary>
        public static string WXGA {
            get {
                return ResourceManager.GetString("WXGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XGA 4:3 (1024x768).
        /// </summary>
        public static string XGA {
            get {
                return ResourceManager.GetString("XGA", resourceCulture);
            }
        }
    }
}
