//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Good_Teacher.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ManualStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ManualStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Good_Teacher.Strings.ManualStrings", typeof(ManualStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the red rectangle are pages - With left click you can select page that you want to modify. Right click on page will open context menu. Currently selected page on image is third in sequence. In blue rectangle are elements that we can add to canvas. With left click on required element we will select element. After that cursor icon will change to image: plus in circle. Left click on canvas will add selected element. With right click or with key ESC you will cancel adding new element. With F5 or click on but [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AddControlToCanvas {
            get {
                return ResourceManager.GetString("AddControlToCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After adding page you will see in the left panel new blank page..
        /// </summary>
        public static string AfterAddingPage {
            get {
                return ResourceManager.GetString("AfterAddingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On bottom panel are special control elements.
        ///
        ///1. Lock - you can lock canvas to disable changes, it can prevent random mistakes. You can unlock it by click on that button again.
        ///
        ///2. Hide page - If you want to hide page from presentation or you want to create special page, which users can only reach by action (button).
        ///
        ///3. Zoom - You can zoom in and zoom out canvas. In textbox is current zoom.
        ///
        ///4. Default zoom - Set zoom to default value: 100%.
        ///
        ///5. Canvas only - Hide everything outside of canvas.
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BottomPanelDescription {
            get {
                return ResourceManager.GetString("BottomPanelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want transfer presentation and you are using specific content like 3D, video or music, you must transfer together presentation file (GTCH) with &quot;Resources&quot; folder..
        /// </summary>
        public static string BuildWarning {
            get {
                return ResourceManager.GetString("BuildWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard shortcuts:
        ///* Ctrl + Mouse wheel - you can zoom in and zoom out.
        ///* Ctrl + Arrows - move canvas to direction
        ///* Page down - change page to +1
        ///* Page up - change page to -1.
        /// </summary>
        public static string CanvasControl {
            get {
                return ResourceManager.GetString("CanvasControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to change canvas settings or presentation settings you must go to settings. You may click on settings button (Cogwheel in green rectangle) or right click on page in left panel and select customize..
        /// </summary>
        public static string CanvasGoToSettings {
            get {
                return ResourceManager.GetString("CanvasGoToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After selecting settings new window appear. You can change background color, canvas size, presentation settings or set background music.
        ///If you want change background you can select in tab 3 sections: color, gradient color or image. 
        ///If you selected color, click on button ( color diagram ) -&gt; select color -&gt; OK.
        ///If you selected gradient color, you can select radial or linear gradient color. Then select both colors ( Start and end ), write your angle and click OK.
        ///If you selected image, click on button a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CanvasSettings {
            get {
                return ResourceManager.GetString("CanvasSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you added elements to canvas, you can edit them. Left click on the control will select it. You can resize it with green and blue points around. You can drag element with left mouse to another position. Also you can change position by dragging rectangle with cross inside it. If control is selected in right panel you will see element settings. You can change it‘s position, size, add effect ( shadow, blur ), change background...
        ///If element is selected you can delete it with delete key or button &quot;Delete&quot; in [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EditingControls {
            get {
                return ResourceManager.GetString("EditingControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the upper left corner, there is an icon (paper with plus) that adds a new page. New page is automatically selected to be edited..
        /// </summary>
        public static string HowToAddPage {
            get {
                return ResourceManager.GetString("HowToAddPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manual is currently incomplete..
        /// </summary>
        public static string Incomplete {
            get {
                return ResourceManager.GetString("Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Start - Add new page, controls....
        /// </summary>
        public static string P1Start {
            get {
                return ResourceManager.GetString("P1Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Canvas settings.
        /// </summary>
        public static string P2Canvas {
            get {
                return ResourceManager.GetString("P2Canvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Image selection.
        /// </summary>
        public static string P3ImageSelection {
            get {
                return ResourceManager.GetString("P3ImageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Editing controls.
        /// </summary>
        public static string P4EditControls {
            get {
                return ResourceManager.GetString("P4EditControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Save and export.
        /// </summary>
        public static string P5SaveExport {
            get {
                return ResourceManager.GetString("P5SaveExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To save your project you can use shortcut Ctrl + S or File -&gt; Save. If you want save to another file then File -&gt; Save As. Every added image is contained in the file. If you don&apos;t use some images, you can remove them in Archive ( button with cabinet ) ( or Tools - &gt; Archive ). You can reduce size of file by removing unused images. Every special content like video, music or 3D model is contained externally in &quot;Resources&quot; folder. Do not rename this folder. If you want use presentation on another computer move [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SaveAndExport {
            get {
                return ResourceManager.GetString("SaveAndExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to set image as background for canvas or element click in the section &quot;image&quot; on button (3 dots). After appearing of new window, you may add new images. You have 3 options: From disk, web or from clipboard.
        ///From disk – Dialog box to select images will appear. Select your image or images and then confirm.
        ///From web - write image url and click OK.
        ///From clipboard - if you have copied image in clipboard, select this option. Window with image preview will appear. Click on Add.
        ///Image will be added  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for using this software. Good Teacher is a free program used for creating interactive presentations, games, graphics and tests..
        /// </summary>
        public static string ThanksForUsing {
            get {
                return ResourceManager.GetString("ThanksForUsing", resourceCulture);
            }
        }
    }
}
